---
# You can add users to the docker group to allow them to manage docker
# containers. This playbook uses sudo rather than the vagrant user because
# Ansible uses ControlPersist for SSH connections. The first time this playbook
# runs, the docker commands would fail if run by the vagrant user, since the
# persisted connection state isn't aware of the addition of the 'docker' group.
- name: Install packages.
  apt: name={{ item }} state=present
  with_items:
    - mc
    - unzip
    - curl
    - git
    - jq
    - python-pip
    - postgresql-client
    - screen


- name: Install Docker Python library.
  pip: name={{ item }} state=present
  with_items:
    - docker
    - yq
